# Generated by Django 5.2.6 on 2025-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(default=1, max_length=100, verbose_name="Название товара"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
    ]
